export type MediaInfo = { company: string; mediaType: string }

export const DOMAIN_MAP: Record<string, MediaInfo> = {
  // ── 통신사 ──────────────────────────────────────────────
  'yna.co.kr':              { company: '연합뉴스',      mediaType: 'Online' },
  'yonhapnews.co.kr':       { company: '연합뉴스',      mediaType: 'Online' },
  'yonhapnewstv.co.kr':     { company: '연합뉴스TV',    mediaType: 'Online' },
  'newsis.com':             { company: '뉴시스',        mediaType: 'Online' },
  'news1.kr':               { company: '뉴스1',         mediaType: 'Online' },

  // ── 방송 ────────────────────────────────────────────────
  'ytn.co.kr':              { company: 'YTN',           mediaType: 'Online' },
  'news.kbs.co.kr':         { company: 'KBS',           mediaType: 'Online' },
  'kbs.co.kr':              { company: 'KBS',           mediaType: 'Online' },
  'news.sbs.co.kr':         { company: 'SBS',           mediaType: 'Online' },
  'sbs.co.kr':              { company: 'SBS',           mediaType: 'Online' },
  'imnews.imbc.com':        { company: 'MBC',           mediaType: 'Online' },
  'imbc.com':               { company: 'MBC',           mediaType: 'Online' },
  'mbc.co.kr':              { company: 'MBC',           mediaType: 'Online' },
  'jtbc.co.kr':             { company: 'JTBC',          mediaType: 'Online' },
  'news.jtbc.co.kr':        { company: 'JTBC',          mediaType: 'Online' },
  'tvchosun.com':           { company: 'TV조선',        mediaType: 'Online' },
  'mbn.co.kr':              { company: 'MBN',           mediaType: 'Online' },
  'ichannela.com':          { company: '채널A',         mediaType: 'Online' },
  'channela.com':           { company: '채널A',         mediaType: 'Online' },

  // ── 종합일간지 ──────────────────────────────────────────
  'chosun.com':             { company: '조선일보',      mediaType: 'Newspaper' },
  'joongang.co.kr':         { company: '중앙일보',      mediaType: 'Newspaper' },
  'donga.com':              { company: '동아일보',      mediaType: 'Newspaper' },
  'hani.co.kr':             { company: '한겨레',        mediaType: 'Newspaper' },
  'hankookilbo.com':        { company: '한국일보',      mediaType: 'Newspaper' },
  'kmib.co.kr':             { company: '국민일보',      mediaType: 'Newspaper' },
  'munhwa.com':             { company: '문화일보',      mediaType: 'Newspaper' },
  'segye.com':              { company: '세계일보',      mediaType: 'Newspaper' },
  'seoul.co.kr':            { company: '서울신문',      mediaType: 'Newspaper' },
  'imaeil.com':             { company: '매일신문',      mediaType: 'Newspaper' },
  'busan.com':              { company: '부산일보',      mediaType: 'Newspaper' },

  // ── 경제지 ──────────────────────────────────────────────
  'hankyung.com':           { company: '한국경제',      mediaType: 'Newspaper' },
  'mk.co.kr':               { company: '매일경제',      mediaType: 'Newspaper' },
  'sedaily.com':            { company: '서울경제',      mediaType: 'Newspaper' },
  'edaily.co.kr':           { company: '이데일리',      mediaType: 'Newspaper' },
  'heraldcorp.com':         { company: '헤럴드경제',    mediaType: 'Newspaper' },
  'mt.co.kr':               { company: '머니투데이',    mediaType: 'Newspaper' },
  'fnnews.com':             { company: '파이낸셜뉴스',  mediaType: 'Newspaper' },
  'etoday.co.kr':           { company: '이투데이',      mediaType: 'Newspaper' },
  'ajunews.com':            { company: '아주경제',      mediaType: 'Newspaper' },
  'asiatoday.co.kr':        { company: '아시아투데이',  mediaType: 'Newspaper' },
  'asiae.co.kr':            { company: '아시아경제',    mediaType: 'Newspaper' },
  'incheonilbo.com':        { company: '인천일보',      mediaType: 'Newspaper' },

  // ── 경제/산업 온라인 ────────────────────────────────────
  'biz.chosun.com':         { company: '조선비즈',      mediaType: 'Online' },
  'thebell.co.kr':          { company: '더벨',          mediaType: 'Online' },
  'businesspost.co.kr':     { company: '비즈니스포스트', mediaType: 'Online' },
  'newspim.com':            { company: '뉴스핌',        mediaType: 'Online' },
  'dailian.co.kr':          { company: '데일리안',      mediaType: 'Online' },
  'news2day.co.kr':         { company: '뉴스투데이',    mediaType: 'Online' },
  'sentv.co.kr':            { company: '서울경제TV',    mediaType: 'Online' },
  'dealsite.co.kr':         { company: '딜사이트',      mediaType: 'Online' },
  'joseilbo.com':           { company: '조세일보',      mediaType: 'Online' },
  'economist.co.kr':        { company: '이코노미스트',  mediaType: 'Online' },
  'sisajournal-e.com':      { company: '시사저널e',     mediaType: 'Online' },
  'businesskorea.co.kr':    { company: 'BusinessKorea', mediaType: 'Online' },
  'theguru.co.kr':          { company: '더구루',        mediaType: 'Online' },
  'thescoop.co.kr':         { company: '더스쿠프',      mediaType: 'Online' },
  'fetv.co.kr':             { company: '팍스경제TV',    mediaType: 'Online' },
  'meconomynews.com':       { company: '매경이코노미',  mediaType: 'Online' },
  'weekly.chosun.com':      { company: '주간조선',      mediaType: 'Online' },

  // ── IT/테크 ─────────────────────────────────────────────
  'etnews.com':             { company: '전자신문',      mediaType: 'IT/Tech' },
  'zdnet.co.kr':            { company: 'ZDNet Korea',   mediaType: 'IT/Tech' },
  'ddaily.co.kr':           { company: '디지털데일리',  mediaType: 'IT/Tech' },
  'inews24.com':            { company: '아이뉴스24',    mediaType: 'IT/Tech' },
  'aitimes.com':            { company: 'AI타임스',      mediaType: 'IT/Tech' },
  'aitimes.kr':             { company: 'AI타임스',      mediaType: 'IT/Tech' },
  'bloter.net':             { company: '블로터',        mediaType: 'IT/Tech' },
  'itchosun.com':           { company: 'IT조선',        mediaType: 'IT/Tech' },
  'itworld.co.kr':          { company: 'IT World',      mediaType: 'IT/Tech' },
  'cio.co.kr':              { company: 'CIO Korea',     mediaType: 'IT/Tech' },
  'digitaltoday.co.kr':     { company: '디지털투데이',  mediaType: 'IT/Tech' },
  'boannews.com':           { company: '보안뉴스',      mediaType: 'IT/Tech' },
  'techrecipe.co.kr':       { company: '테크레시피',    mediaType: 'IT/Tech' },
  'epnc.co.kr':             { company: '전자부품',      mediaType: 'IT/Tech' },
  'itbiznews.com':          { company: 'IT비즈뉴스',   mediaType: 'IT/Tech' },
  'eroun.net':              { company: '이로운넷',      mediaType: 'IT/Tech' },
  'dnews.co.kr':            { company: '대한경제',      mediaType: 'IT/Tech' },
  'ciokorea.com':           { company: 'CIO Korea',     mediaType: 'IT/Tech' },
  'itdaily.kr':             { company: 'IT데일리',      mediaType: 'IT/Tech' },
  'datanet.co.kr':          { company: '데이터넷',      mediaType: 'IT/Tech' },
  'comworld.co.kr':         { company: '컴퓨터월드',    mediaType: 'IT/Tech' },
  'betanews.net':           { company: '베타뉴스',      mediaType: 'IT/Tech' },
  'venturesquare.net':      { company: '벤처스퀘어',    mediaType: 'IT/Tech' },
  'hellodd.com':            { company: '헬로디디',       mediaType: 'IT/Tech' },
  'kbench.com':             { company: '케이벤치',       mediaType: 'IT/Tech' },
  'jndn.com':               { company: '전남일보',       mediaType: 'Online' },
  'dream.kotra.or.kr':      { company: 'KOTRA',          mediaType: 'Online' },
  'lkp.news':               { company: 'LKP뉴스',        mediaType: 'Online' },
  'startuptoday.co.kr':    { company: '스타트업투데이', mediaType: 'IT/Tech' },
  'it-b.co.kr':            { company: '아이티비즈',     mediaType: 'IT/Tech' },
  'news.mtn.co.kr':        { company: 'MTN뉴스',        mediaType: 'Online' },
  'mtn.co.kr':             { company: 'MTN뉴스',        mediaType: 'Online' },
  'platum.kr':              { company: '플래텀',        mediaType: 'IT/Tech' },
  'byline.network':         { company: '바이라인네트워크', mediaType: 'IT/Tech' },
  'techm.kr':               { company: '테크M',         mediaType: 'IT/Tech' },
  'theeconomy.co.kr':       { company: 'The Economy',   mediaType: 'IT/Tech' },
  'thelec.net':             { company: '더일렉',        mediaType: 'IT/Tech' },
  'dt.co.kr':               { company: '디지털타임스',  mediaType: 'IT/Tech' },
  'kipost.net':             { company: '키포스트',      mediaType: 'IT/Tech' },
  'eetkorea.com':           { company: 'EE타임스코리아', mediaType: 'IT/Tech' },
  'bizwatch.co.kr':         { company: '비즈워치',      mediaType: 'Online' },
  'moneys.co.kr':           { company: '머니S',         mediaType: 'Online' },
  'paxnetnews.com':         { company: '팍스넷뉴스',    mediaType: 'Online' },
  'ohmynews.com':           { company: '오마이뉴스',    mediaType: 'Online' },
  'pressian.com':           { company: '프레시안',      mediaType: 'Online' },
  'dhnews.co.kr':           { company: '대학저널',      mediaType: 'Online' },
  'enewstoday.co.kr':       { company: '이뉴스투데이',  mediaType: 'Online' },

  // ── 추가 매체 ───────────────────────────────────────────
  'widedaily.com':          { company: '와이드데일리',  mediaType: 'Online' },
  'theasian.asia':          { company: '더아시안',      mediaType: 'Online' },
  'starnewskorea.com':      { company: '스타뉴스',      mediaType: 'Online' },
  'ziksir.com':             { company: '직썰',          mediaType: 'Online' },
  'tokenpost.kr':           { company: '토큰포스트',    mediaType: 'IT/Tech' },
  'financialpost.co.kr':   { company: '파이낸셜포스트', mediaType: 'Online' },
  'g-enews.com':            { company: '글로벌이코노믹', mediaType: 'Online' },
  'hansbiz.co.kr':          { company: '한스경제',      mediaType: 'Online' },
  'jnilbo.com':             { company: '전남일보',      mediaType: 'Online' },
  'autodaily.co.kr':        { company: '오토데일리',    mediaType: 'Online' },
  'asiatime.co.kr':         { company: '아시아타임즈',  mediaType: 'Online' },
  'cbci.co.kr':             { company: 'CBS노컷뉴스',   mediaType: 'Online' },
  'insight.co.kr':          { company: '인사이트',      mediaType: 'Online' },
  'srtimes.kr':             { company: 'SR타임스',       mediaType: 'Online' },
  'khan.co.kr':             { company: '경향신문',      mediaType: 'Newspaper' },
  'wowtv.co.kr':            { company: '한국경제TV',    mediaType: 'Online' },
  'ebn.co.kr':              { company: 'EBN',           mediaType: 'Online' },
  'fntoday.co.kr':          { company: '파이낸셜투데이', mediaType: 'Online' },
  'econovill.com':          { company: '이코노믹리뷰',  mediaType: 'Online' },
  'womaneconomy.co.kr':     { company: '여성경제신문',  mediaType: 'Online' },
  'weeklytrade.co.kr':      { company: '주간무역',      mediaType: 'Online' },
  'appstory.co.kr':         { company: '앱스토리',      mediaType: 'IT/Tech' },
  'wikileaks-kr.org':       { company: '위키리크스한국', mediaType: 'Online' },
  'dongponews.net':         { company: '동포뉴스',      mediaType: 'Online' },
  'thepublic.kr':           { company: '더퍼블릭',      mediaType: 'Online' },
  'the-biz.co.kr':          { company: '더비즈',        mediaType: 'Online' },
  'e-science.co.kr':        { company: '이코노미사이언스', mediaType: 'Online' },
  'nongmin.com':            { company: '농민신문',      mediaType: 'Newspaper' },
  'newstomato.com':         { company: '뉴스토마토',    mediaType: 'Online' },
  'delighti.co.kr':         { company: '딜라이트닷넷',  mediaType: 'Online' },
  'obsnews.co.kr':          { company: 'OBS경인TV',     mediaType: 'Online' },
  'kbmaeil.com':            { company: '경북매일',      mediaType: 'Newspaper' },
  'gokorea.kr':             { company: '공감신문',      mediaType: 'Online' },
  'newdaily.co.kr':         { company: '뉴데일리',      mediaType: 'Online' },
  'einfomax.co.kr':         { company: '연합인포맥스',  mediaType: 'Online' },
}

/** collector.ts용 단순 domain → company 이름 맵 */
export const ALLOWED_DOMAINS: Record<string, string> = Object.fromEntries(
  Object.entries(DOMAIN_MAP).map(([domain, info]) => [domain, info.company])
)

/** collector.ts SOURCE_NAME_MAP용 */
export const SOURCE_NAME_MAP: Record<string, string> = {
  // 통신사
  'Yonhap News Agency': '연합뉴스',
  'Yonhap': '연합뉴스',
  'Yonhap News TV': '연합뉴스TV',
  'Newsis': '뉴시스',
  'News1': '뉴스1',
  // 방송
  'YTN': 'YTN',
  'KBS': 'KBS',
  'KBS News': 'KBS',
  'SBS': 'SBS',
  'SBS News': 'SBS',
  'MBC': 'MBC',
  'JTBC': 'JTBC',
  'TV Chosun': 'TV조선',
  'MBN': 'MBN',
  'Channel A': '채널A',
  // 종합일간지
  'The Chosun Ilbo': '조선일보',
  'JoongAng Ilbo': '중앙일보',
  'Donga': '동아일보',
  'Hankyoreh': '한겨레',
  'Hankook Ilbo': '한국일보',
  'Kookmin Ilbo': '국민일보',
  'Munhwa Ilbo': '문화일보',
  'Segye Ilbo': '세계일보',
  // 경제지
  'Korea Economic Daily': '한국경제',
  'Maeil Business Newspaper': '매일경제',
  'Seoul Economic Daily': '서울경제',
  'Edaily': '이데일리',
  'The Korea Herald': '헤럴드경제',
  'Money Today': '머니투데이',
  'Financial News': '파이낸셜뉴스',
  'The Bell': '더벨',
  'Aju News': '아주경제',
  'Asia Today': '아시아투데이',
  'Asia Economy': '아시아경제',
  // IT/테크
  'Electronic Times': '전자신문',
  'ZDNet Korea': 'ZDNet Korea',
  'Digital Daily': '디지털데일리',
  'iNews24': '아이뉴스24',
  'AI Times': 'AI타임스',
  'Bloter': '블로터',
  'IT Chosun': 'IT조선',
  'Digital Today': '디지털투데이',
  'BusinessKorea': 'BusinessKorea',
  'The Guru': '더구루',
  'The Scoop': '더스쿠프',
  // 경제/산업
  'ChosunBiz': '조선비즈',
  'BusinessPost': '비즈니스포스트',
  'Newspim': '뉴스핌',
  'Dailian': '데일리안',
  'The Elec': '더일렉',
  'Digital Times': '디지털타임스',
  'Kipost': '키포스트',
  'EE Times Korea': 'EE타임스코리아',
  'BizWatch': '비즈워치',
  'OhmyNews': '오마이뉴스',
  'Pressian': '프레시안',
}
